// constants/errorCodes.js
export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  ACCESS_DENIED: "ACCESS_DENIED",

  VALIDATION_FAILED: "VALIDATION_FAILED",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",

  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
